### ISSUE TITLE
TFCE bug - find Assertion failed

### ISSUE THREAD

**Issue by nicholst** [NISOx-BDI/SwE-toolbox#63] opened 2018-10-18 05:55 UTC
Use for issues related to the new implementation of TFCE (PR #48, Issue #15)

**Comment by nicholst** [comment] 2018-10-18 06:01
From 'Sid Chopra'
> Thanks for sharing the pre-release. I gave it a spin and while the voxel and cluster-level inference still runs fine, I get the below error with TFCE inference:
> Unable to perform assignment because the left and right sides have a different number of elements.

```matlab
Error in swe_cp_WB (line 1643)
            scorevol(sub2ind(DIM,XYZ(1,:),XYZ(2,:),XYZ(3,:))) =
            swe_invNcdf(pvol);
 
MATLAB: management.cpp:671: find: Assertion `' failed.
MATLAB: management.cpp:671: find: Assertion `' failed.
```

> This error seems to occur after the first bootstrap:
```
Initialising parameters                 :                        ...done
Output images                           :                 ...initialised
                ...initialised
Plane 121/121, block   1/1              :                        ...done
Saving results                          :                     ...writing
Bootstrap # 1  Block 10/10              :  
```

> Please let me know if you require further info.

**Comment by nicholst** [comment] 2018-10-18 06:02
@TomMaullin Ideas on this?

**Comment by TomMaullin** [comment] 2018-10-18 13:36
Hi @nicholst ,

I believe, after going over the code in a lot of detail, I have found the cause of this bug. I believe it is probably due to the variable `blksz` not being used correctly. This variable is used for handling the situation when there is not enough memory available. The SwE toolbox breaks the analysis into blocks of size `blksz` and then computes block by block. The P values are split into their relevant block sizes in the current code (e.g. `size(pvol) = [1 blksz]`) but the XYZ coordinates are not (e.g. `size(XYZ) = [1 {mask size}] ~= [1 blksz]`).

The reason I had not come across this error during testing was most likely due to the fact the example analyses I use do not take as much memory and are much simpler than what I imagine many users are doing.

I hope to have a PR for a fix for this shortly.

**Comment by nicholst** [comment] 2018-10-18 13:41
Thanks @TomMaullin!

**Comment by sidchop** [comment] 2018-10-21 07:13
Thanks! TFCE inference now seems to be working smoothing.

**Comment by TomMaullin** [comment] 2018-10-22 09:36
Ah great! Thank you Sid!

**Comment by TomMaullin** [comment] 2018-10-22 09:36
Ah great! Thank you Sid!

**Closed by TomMaullin** 2018-10-22 09:36 UTC

**Comment by sidchop** [comment] 2018-11-12 05:47
Hey Tom,
Just wanted to check if there were any substantive differences in the TFCE calculation between the SwE version you sent me (2.0.0rc) and the recently released version. Will I need to re-run my analyses?

Thanks,
Sid

**Comment by TomMaullin** [comment] 2018-11-12 10:12
Hi Sid,

I believe the TFCE calculation itself is identical to the version you were using! The largest differences between `v2.0.0rc` and `v2.0.0` were that:

 - "classic" SwE analyses would not run in `v2.0.0rc` but will run in `v2.0.0`
 - some analyses in `v2.0.0rc` would run into memory issues if they were particularly large. This is not a problem in `v2.0.0`.

In short, the only fixes were for analyses that would not run in `v2.0.0rc`. If your analysis ran in `v2.0.0rc`, I believe it should be the same as you would have obtained in `v2.0.0`.

Cheers,
Tom M
