### ISSUE TITLE
Use of "Change Significance" creates error WB results

### ISSUE THREAD

**Issue by nicholst** [NISOx-BDI/SwE-toolbox#107] opened 2019-05-08 07:25 UTC
At present, nothing stops a user from using the Change Significance menu... but of course this isn't possible for WB (or, at least, only the FWE threshold can be changed).

Trying to use it creates an error:

```
Index exceeds matrix dimensions.

Error in swe_getSPM (line 541)
      str  = xCon(Ic).name;

Error in swe_results_ui (line 245)
        [SwE,xSwE] = swe_getSPM(varargin{2});

Error in swe_results_ui>mychgcon (line 1232)
[hReg,xSwE,SwE] = swe_results_ui('setup',xSwE2);
 
Error while evaluating DestroyedObject Callback
```

**Comment by BryanGuillaume** [comment] 2019-07-12 14:56
I believe this has been fixed through the changes introduced in PR #125 and maybe also in PR #131. Currently, I cannot reproduced any error of this sort when I am using the "Change Significance" menu . Thus, I am closing this issue.

**Closed by BryanGuillaume** 2019-07-12 14:56 UTC
Labels: bug
